# Generated by Django 2.1.7 on 2019-03-28 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tournament',
            name='match',
        ),
        migrations.AddField(
            model_name='tournament',
            name='match',
            field=models.ManyToManyField(to='tournaments.Match'),
        ),
    ]
