# Generated by Django 2.1.7 on 2019-03-28 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0002_auto_20190328_0112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tournament',
            old_name='match',
            new_name='matches',
        ),
    ]
